paytm.payment:
  config:
    merchantId: KNjRJs68463218233452
    merchantKey: NNsiiRv6v@GXBKi#
    channelId: WEB
    website: WEBSTAGING
    industryTypeId: Education
    paytmUrl:  https://securegw-stage.paytm.in/order/process
    callbackUrl: http://localhost:9094/pgresponse
    details:
      MID: ${paytm.payment.config.merchantid}
      CHANNEL_ID: WEB
      INDUSTRY_TYPE_ID: Education
      WEBSITE: WEBSTAGING
      CALLBACK_URL: ${paytm.payment.config.callbackUrl}


